import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/module/Footer/Footer";
import Header from "@/components/module/Header/Header";
import ReduxProvider from "./(redux)/ReduxProvider";

export const metadata: Metadata = {
  title: "Saghfinoo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
